// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMCPRoutes implements MCPRouteInterface
type fakeMCPRoutes struct {
	*gentype.FakeClientWithList[*v1beta1.MCPRoute, *v1beta1.MCPRouteList]
	Fake *FakeAigatewayV1beta1
}

func newFakeMCPRoutes(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.MCPRouteInterface {
	return &fakeMCPRoutes{
		gentype.NewFakeClientWithList[*v1beta1.MCPRoute, *v1beta1.MCPRouteList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("mcproutes"),
			v1beta1.SchemeGroupVersion.WithKind("MCPRoute"),
			func() *v1beta1.MCPRoute { return &v1beta1.MCPRoute{} },
			func() *v1beta1.MCPRouteList { return &v1beta1.MCPRouteList{} },
			func(dst, src *v1beta1.MCPRouteList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.MCPRouteList) []*v1beta1.MCPRoute { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.MCPRouteList, items []*v1beta1.MCPRoute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
